// export const icons = [
//   "typescript",
//   "javascript",
//   "java",
//   "react",
//   "html5",
//   "css3",
//   "nodedotjs",
//   "express",
//   "nextdotjs",
//   "prisma",
//   "postgresql",
//   "firebase",
//   "vercel",
//   "testinglibrary",
//   "jest",
//   "cypress",
//   "docker",
//   "git",
//   "jira",
//   "github",
//   "gitlab",
//   "visualstudiocode",
//   "figma",
//   "openai",
//   "python",
// ];

export const icons = ["adobeillustrator","adobephotoshop","adobexd","alpinedotjs","amazonwebservices","androidstudio","apache","apachetomcat","axios","centos","figma","cts","css3","daisyui","elementor","electron","git","github","gitlab","googlesearchconsole","googlemaps","html5","informatica","laragon","laravel","nextdotjs","ngrok","nginx","mysql","php","react","vuedotjs","jquery","ubuntu","javascript","tailwindcss"];
